name: Code formatting

on:
  push:
    branches: [ main ]

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install code beautifier
      run: make install-beautifier
      
    - name: Magik
      run: make beautify

    - name: Commit those back
      uses: EndBug/add-and-commit@v9.1.1
      with:
        message: "Beautified"
        author_name: "Code beautifier"
